services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=openpgpwd  # Directly set the database password here
      - DB_HOST=db
      - DB_PORT=5432
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"] 

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=openpgpwd  # Set the same password here
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data: